In [301]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import tree

In [302]:
sayaDataset = pd.read_csv('klasifikasi_sayaDataset1.csv', 
                          delimiter=';', header=0)

In [303]:
sayaDataset.head()

No_Absen  Tugas  UTS  UAS  Rata_Nilai Naik_Kelas
0         1      7    8    6           7       naik
1         2      7    7    7           7       naik
2         3      6    6    7           6      tidak
3         4      8    8    7           7       naik
4         5      5    5    7           6      tidak

In [304]:
sayaDataset["Naik_Kelas"] = pd.factorize(sayaDataset.Naik_Kelas)[0]

In [305]:
sayaDataset.head()

No_Absen  Tugas  UTS  UAS  Rata_Nilai  Naik_Kelas
0         1      7    8    6           7           0
1         2      7    7    7           7           0
2         3      6    6    7           6           1
3         4      8    8    7           7           0
4         5      5    5    7           6           1

In [306]:
print(irisDataset)

[[7.   3.02 4.07 1.04 0.  ]
 [6.04 3.02 4.05 1.05 0.  ]
 [6.09 3.01 4.09 1.05 0.  ]
 [5.05 2.03 4.   1.03 0.  ]
 [6.05 2.08 4.06 1.05 0.  ]
 [5.07 2.08 4.05 1.03 0.  ]
 [6.03 3.03 4.07 1.06 0.  ]
 [4.09 2.04 3.03 1.   0.  ]
 [6.06 2.09 4.06 1.03 0.  ]
 [5.02 2.07 3.09 1.04 0.  ]
 [5.   2.   3.05 1.   0.  ]
 [5.09 3.   4.02 1.05 0.  ]
 [6.   2.02 4.   1.   0.  ]
 [6.01 2.09 4.07 1.04 0.  ]
 [5.06 2.09 3.06 1.03 0.  ]
 [6.07 3.01 4.04 1.04 0.  ]
 [5.06 3.   4.05 1.05 0.  ]
 [5.08 2.07 4.01 1.   0.  ]
 [6.02 2.02 4.05 1.05 0.  ]
 [5.06 2.05 3.09 1.01 0.  ]
 [5.09 3.02 4.08 1.08 0.  ]
 [6.01 2.08 4.   1.03 0.  ]
 [6.03 2.05 4.09 1.05 0.  ]
 [6.01 2.08 4.07 1.02 0.  ]
 [6.04 2.09 4.03 1.03 0.  ]
 [6.06 3.   4.04 1.04 0.  ]
 [6.08 2.08 4.08 1.04 0.  ]
 [6.07 3.   5.   1.07 0.  ]
 [6.   2.09 4.05 1.05 0.  ]
 [5.07 2.06 3.05 1.   0.  ]
 [5.05 2.04 3.08 1.01 0.  ]
 [5.05 2.04 3.07 1.   0.  ]
 [5.08 2.07 3.09 1.02 0.  ]
 [6.   2.07 5.01 1.06 0.  ]
 [5.04 3.   4.05 1.05 0.  ]
 [6.   3.04 4.05 1.0

In [307]:
sayaDataset = sayaDataset.drop(labels="No_Absen", axis=1)

In [308]:
print(sayaDataset)

    Tugas  UTS  UAS  Rata_Nilai  Naik_Kelas
0       7    8    6           7           0
1       7    7    7           7           0
2       6    6    7           6           1
3       8    8    7           7           0
4       5    5    7           6           1
5       7    7    6           6           1
6       7    7    7           7           0
7       7    7    8           7           0
8       7    7    6           7           0
9       7    7    7           7           0
10      7    7    8           7           0
11      7    7    9           7           0
12      7    7    7           7           0
13      7    7    8           7           0
14      7    7    6           6           1
15      7    7    8           7           0
16      7    7    9           7           0
17      7    7    5           6           1
18      7    6    8           7           0
19      7    7    7           7           0
20      7    8    8           7           0
21      6    6    9           7 

In [309]:
sayaDataset = sayaDataset.to_numpy()

In [310]:
print(sayaDataset)

[[7 8 6 7 0]
 [7 7 7 7 0]
 [6 6 7 6 1]
 [8 8 7 7 0]
 [5 5 7 6 1]
 [7 7 6 6 1]
 [7 7 7 7 0]
 [7 7 8 7 0]
 [7 7 6 7 0]
 [7 7 7 7 0]
 [7 7 8 7 0]
 [7 7 9 7 0]
 [7 7 7 7 0]
 [7 7 8 7 0]
 [7 7 6 6 1]
 [7 7 8 7 0]
 [7 7 9 7 0]
 [7 7 5 6 1]
 [7 6 8 7 0]
 [7 7 7 7 0]
 [7 8 8 7 0]
 [6 6 9 7 1]
 [6 7 7 6 1]
 [6 8 6 6 1]
 [6 9 8 7 0]
 [7 7 7 7 0]
 [5 8 6 6 1]
 [5 6 5 5 1]
 [5 8 7 6 1]
 [5 9 8 7 1]
 [5 5 9 6 1]
 [5 8 9 7 1]
 [5 7 7 6 1]
 [5 8 6 6 1]
 [5 9 7 7 0]
 [5 7 8 6 1]
 [5 6 7 6 1]
 [5 8 5 6 1]
 [7 7 7 7 0]
 [8 6 6 6 1]
 [6 5 7 6 1]
 [6 7 8 7 0]
 [9 8 9 8 0]
 [8 9 8 8 0]
 [7 9 7 7 0]
 [7 7 8 7 0]
 [5 6 6 5 1]
 [5 7 7 6 1]
 [5 8 8 7 1]
 [7 7 6 6 1]
 [8 5 7 6 1]
 [6 7 8 7 0]
 [6 6 9 7 0]
 [9 7 7 7 0]
 [8 8 8 8 0]
 [7 9 6 7 0]
 [7 8 8 7 0]
 [6 7 9 7 0]
 [8 8 5 7 0]]


In [311]:
dataTraining = np.concatenate((sayaDataset[0:30, :],
                               sayaDataset[40:50, :]), axis=0)
dataTesting = np.concatenate((sayaDataset[30:40, :],
                               sayaDataset[50:60, :]), axis=0)

In [312]:
print(dataTraining)
len(dataTraining)

[[7 8 6 7 0]
 [7 7 7 7 0]
 [6 6 7 6 1]
 [8 8 7 7 0]
 [5 5 7 6 1]
 [7 7 6 6 1]
 [7 7 7 7 0]
 [7 7 8 7 0]
 [7 7 6 7 0]
 [7 7 7 7 0]
 [7 7 8 7 0]
 [7 7 9 7 0]
 [7 7 7 7 0]
 [7 7 8 7 0]
 [7 7 6 6 1]
 [7 7 8 7 0]
 [7 7 9 7 0]
 [7 7 5 6 1]
 [7 6 8 7 0]
 [7 7 7 7 0]
 [7 8 8 7 0]
 [6 6 9 7 1]
 [6 7 7 6 1]
 [6 8 6 6 1]
 [6 9 8 7 0]
 [7 7 7 7 0]
 [5 8 6 6 1]
 [5 6 5 5 1]
 [5 8 7 6 1]
 [5 9 8 7 1]
 [6 5 7 6 1]
 [6 7 8 7 0]
 [9 8 9 8 0]
 [8 9 8 8 0]
 [7 9 7 7 0]
 [7 7 8 7 0]
 [5 6 6 5 1]
 [5 7 7 6 1]
 [5 8 8 7 1]
 [7 7 6 6 1]]


40

In [313]:
print(dataTesting)
len(dataTesting)

[[5 5 9 6 1]
 [5 8 9 7 1]
 [5 7 7 6 1]
 [5 8 6 6 1]
 [5 9 7 7 0]
 [5 7 8 6 1]
 [5 6 7 6 1]
 [5 8 5 6 1]
 [7 7 7 7 0]
 [8 6 6 6 1]
 [8 5 7 6 1]
 [6 7 8 7 0]
 [6 6 9 7 0]
 [9 7 7 7 0]
 [8 8 8 8 0]
 [7 9 6 7 0]
 [7 8 8 7 0]
 [6 7 9 7 0]
 [8 8 5 7 0]]


19

In [314]:
inputTraining = dataTraining[:,0:4]
inputTesting = dataTesting[:,0:4]
labelTraining = dataTraining[:,4]
labelTesting = dataTesting[:, 4]

In [315]:
model = tree.DecisionTreeClassifier()

In [316]:
model = model.fit(inputTraining, labelTraining)

In [317]:
hasilPrediksi = model.predict(inputTesting)
print("label sebenarnya", labelTesting)
print("hasil prediksi:", hasilPrediksi)

label sebenarnya [1 1 1 1 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0]
hasil prediksi: [1 1 1 1 1 1 1 1 0 1 1 0 1 0 0 0 0 0 0]


In [318]:
prediksiBenar = (hasilPrediksi == labelTesting).sum() 
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("prediksi benar: ", prediksiBenar, "data")
print("prediksi salah: ", prediksiSalah, "data")
print("akurasi: ", prediksiBenar/(prediksiBenar+prediksiSalah)
      * 100, "%")

prediksi benar:  17 data
prediksi salah:  2 data
akurasi:  89.47368421052632 %


In [319]:
iris = datasets.load_iris()
features = iris['data']
target = iris['target']

In [320]:
print(features)
len(features)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

150

In [321]:
print(target)
len(target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


150

In [322]:
decisiontree = DecisionTreeClassifier(random_state=0,
                                      max_depth=None, min_samples_split=2, 
                                      min_samples_leaf=1, min_weight_fraction_leaf=0, 
                                      max_leaf_nodes=None, min_impurity_decrease=0)

In [323]:
model = decisiontree.fit(features, target)

In [324]:
observation = [[5, 4, 3, 2]]
model.predict(observation)
model.predict_proba(observation)

array([[0., 1., 0.]])

In [325]:
import pydotplus
from sklearn import tree
dot_data = tree.export_graphviz(decisiontree, out_file=None,
                                feature_names=iris['feature_names'], class_names=iris['target_names'])
from IPython.display import Image
graph = pydotplus.graph_from_dot_data(dot_data)
Image(graph.create_png())
graph.write_png("data.png")

True