In [262]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [263]:
dataset = pd.read_csv('EU_Bank_churn_2017.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [264]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [265]:
print(X)

[[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 'Female' 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 'Female' 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 'Female' 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 'Female' 43 2 125510.82 1 1 1 79084.1]
 [645 'Spain' 'Male' 44 8 113755.78 2 1 0 149756.71]
 [822 'France' 'Male' 50 7 0.0 2 1 1 10062.8]
 [376 'Germany' 'Female' 29 4 115046.74 4 1 0 119346.88]
 [501 'France' 'Male' 44 4 142051.07 2 0 1 74940.5]
 [684 'France' 'Male' 27 2 134603.88 1 1 1 71725.73]
 [528 'France' 'Male' 31 6 102016.72 2 0 0 80181.12]
 [497 'Spain' 'Male' 24 3 0.0 2 1 0 76390.01]
 [476 'France' 'Female' 34 10 0.0 2 1 0 26260.98]
 [549 'France' 'Female' 25 5 0.0 2 0 0 190857.79]
 [635 'Spain' 'Female' 35 7 0.0 2 1 1 65951.65]
 [616 'Germany' 'Male' 45 3 143129.41 2 0 1 64327.26]
 [653 'Germany' 'Male' 58 1 132602.88 1 1 0 5097.67]
 [549 'Spain' 'Female' 24 9 0.0 2 1 1 14406.41]
 [587 'Spain' 'Male' 45 6 0.0 1 0 0 158684.81]
 [726 'France' 'Female' 24 6 

In [266]:
print(y)

[1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0]


In [267]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder = LabelEncoder()
X[:, 2] = labelencoder.fit_transform(X[:, 2])

In [268]:
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(columnTransformer.fit_transform(X), dtype = np.float)

In [269]:
X = X[:, 1:]

In [270]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [271]:
print(X_train)

[[0.0000000e+00 1.0000000e+00 6.0800000e+02 0.0000000e+00 4.1000000e+01
  1.0000000e+00 8.3807860e+04 1.0000000e+00 0.0000000e+00 1.0000000e+00
  1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.4900000e+02 0.0000000e+00 2.5000000e+01
  5.0000000e+00 0.0000000e+00 2.0000000e+00 0.0000000e+00 0.0000000e+00
  1.9085779e+05]
 [0.0000000e+00 0.0000000e+00 6.6900000e+02 1.0000000e+00 4.6000000e+01
  3.0000000e+00 0.0000000e+00 2.0000000e+00 0.0000000e+00 1.0000000e+00
  8.4877500e+03]
 [1.0000000e+00 0.0000000e+00 6.5300000e+02 1.0000000e+00 5.8000000e+01
  1.0000000e+00 1.3260288e+05 1.0000000e+00 1.0000000e+00 0.0000000e+00
  5.0976700e+03]
 [0.0000000e+00 0.0000000e+00 5.0100000e+02 1.0000000e+00 4.4000000e+01
  4.0000000e+00 1.4205107e+05 2.0000000e+00 0.0000000e+00 1.0000000e+00
  7.4940500e+04]
 [0.0000000e+00 0.0000000e+00 8.2200000e+02 1.0000000e+00 5.0000000e+01
  7.0000000e+00 0.0000000e+00 2.0000000e+00 1.0000000e+00 1.0000000e+00
  1.0062800e+04]
 [0.0000000e+00 1.0000000e+00 5.49

In [272]:
print(X_test)

[[0.0000000e+00 1.0000000e+00 4.9700000e+02 1.0000000e+00 2.4000000e+01
  3.0000000e+00 0.0000000e+00 2.0000000e+00 1.0000000e+00 0.0000000e+00
  7.6390010e+04]
 [0.0000000e+00 0.0000000e+00 5.2800000e+02 1.0000000e+00 3.1000000e+01
  6.0000000e+00 1.0201672e+05 2.0000000e+00 0.0000000e+00 0.0000000e+00
  8.0181120e+04]
 [0.0000000e+00 1.0000000e+00 5.1000000e+02 0.0000000e+00 3.8000000e+01
  4.0000000e+00 0.0000000e+00 1.0000000e+00 1.0000000e+00 0.0000000e+00
  1.1891353e+05]
 [0.0000000e+00 1.0000000e+00 6.3500000e+02 0.0000000e+00 3.5000000e+01
  7.0000000e+00 0.0000000e+00 2.0000000e+00 1.0000000e+00 1.0000000e+00
  6.5951650e+04]
 [0.0000000e+00 0.0000000e+00 7.3200000e+02 1.0000000e+00 4.1000000e+01
  8.0000000e+00 0.0000000e+00 2.0000000e+00 1.0000000e+00 1.0000000e+00
  1.7088617e+05]]


In [273]:
print(y_train)

[0 0 0 1 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0]


In [274]:
print(y_test)

[0 0 1 0 0]


In [275]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [276]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [277]:
MesinKlasifikasi = Sequential()
MesinKlasifikasi.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
MesinKlasifikasi.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
MesinKlasifikasi.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
MesinKlasifikasi.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
MesinKlasifikasi.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
2/2 [==============================] - 1s 6ms/step - loss: 0.6930 - accuracy: 0.7246
Epoch 2/100
2/2 [==============================] - 0s 10ms/step - loss: 0.6925 - accuracy: 0.7579
Epoch 3/100
2/2 [==============================] - 0s 7ms/step - loss: 0.6920 - accuracy: 0.7579
Epoch 4/100
2/2 [==============================] - 0s 14ms/step - loss: 0.6912 - accuracy: 0.7912
Epoch 5/100
2/2 [==============================] - 0s 4ms/step - loss: 0.6909 - accuracy: 0.7579
Epoch 6/100
2/2 [==============================] - 0s 5ms/step - loss: 0.6906 - accuracy: 0.7246
Epoch 7/100
2/2 [==============================] - 0s 4ms/step - loss: 0.6906 - accuracy: 0.6912
Epoch 8/100
2/2 [==============================] - 0s 7ms/step - loss: 0.6906 - accuracy: 0.6579
Epoch 9/100
2/2 [==============================] - 0s 10ms/step - loss: 0.6892 - accuracy: 0.7246
Epoch 10/100
2/2 [==============================] - 0s 4ms/step - loss: 0.6887 - accuracy: 0.7246
Epoch 11/100
2/2 [========

In [278]:
y_pred = MesinKlasifikasi.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)