In [434]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [435]:
dataset = pd.read_csv('Data1.csv')


In [436]:
dataset.head()

Kota  Usia  Pendapatan Asuransi
0    Semarang  44.0     72000.0    Tidak
1   Surakarta  27.0     48000.0       Ya
2    Salatiga  30.0     54000.0    Tidak
3      Klaten  38.0     61000.0    Tidak
4  Pekalongan  40.0         NaN       Ya

In [437]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [438]:
print(x)

[['Semarang' 44.0 72000.0]
 ['Surakarta' 27.0 48000.0]
 ['Salatiga' 30.0 54000.0]
 ['Klaten' 38.0 61000.0]
 ['Pekalongan' 40.0 nan]
 ['Cilacap' 35.0 58000.0]
 ['Kudus' nan 52000.0]
 ['Tegal' 48.0 79000.0]
 ['Surakarta' 50.0 83000.0]
 ['Semarang' 37.0 67000.0]]


In [439]:
print(y)

['Tidak' 'Ya' 'Tidak' 'Tidak' 'Ya' 'Ya' 'Tidak' 'Ya' 'Tidak' 'Ya']


In [440]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [441]:
print(x)

[['Semarang' 44.0 72000.0]
 ['Surakarta' 27.0 48000.0]
 ['Salatiga' 30.0 54000.0]
 ['Klaten' 38.0 61000.0]
 ['Pekalongan' 40.0 63777.77777777778]
 ['Cilacap' 35.0 58000.0]
 ['Kudus' 38.77777777777778 52000.0]
 ['Tegal' 48.0 79000.0]
 ['Surakarta' 50.0 83000.0]
 ['Semarang' 37.0 67000.0]]


In [442]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [443]:
print(x)

[[0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 27.0 48000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 38.77777777777778 52000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 48.0 79000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


In [444]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [445]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [446]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [447]:
print(x_train)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 38.77777777777778 52000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 27.0 48000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 48.0 79000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 35.0 58000.0]]


In [448]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


In [449]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [450]:
print(y_test)

[0 1]


In [451]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [452]:
print(x_train)

[[0.0 0.0 1.0 -0.3779644730092272 0.0 -0.3779644730092272
  -0.5773502691896258 -0.3779644730092272 -0.19159184384578545
  -1.0781259408412425]
 [0.0 0.0 0.0 2.6457513110645903 0.0 -0.3779644730092272
  -0.5773502691896258 -0.3779644730092272 -0.014117293757057777
  -0.07013167641635372]
 [0.0 0.0 0.0 -0.3779644730092272 0.0 2.6457513110645903
  -0.5773502691896258 -0.3779644730092272 0.566708506533324
  0.633562432710455]
 [0.0 1.0 0.0 -0.3779644730092272 0.0 -0.3779644730092272
  -0.5773502691896258 -0.3779644730092272 -0.30453019390224867
  -0.30786617274297867]
 [0.0 0.0 0.0 -0.3779644730092272 0.0 -0.3779644730092272
  1.7320508075688774 -0.3779644730092272 -1.9018011447007988
  -1.420463615551582]
 [0.0 0.0 0.0 -0.3779644730092272 0.0 -0.3779644730092272
  -0.5773502691896258 2.6457513110645903 1.1475343068237058
  1.232653363453549]
 [0.0 0.0 0.0 -0.3779644730092272 0.0 -0.3779644730092272
  1.7320508075688774 -0.3779644730092272 1.4379472069688968
  1.5749910381638885]
 [1.0 0.

In [453]:
print(x_test)

[[0.0 0.0 0.0 -0.3779644730092272 1.0 -0.3779644730092272
  -0.5773502691896258 -0.3779644730092272 -1.4661817944830124
  -0.9069571034860727]
 [0.0 0.0 0.0 -0.3779644730092272 0.0 2.6457513110645903
  -0.5773502691896258 -0.3779644730092272 -0.44973664397484414
  0.2056403393225306]]
